name: Sync to Hugging Face Hub
on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true
          fetch-depth: 0  # Fetch the full history

      - name: Set up Git
        run: |
          git config --global user.email "manasabrao2020@gmail.com.com"
          git config --global user.name "Manasa B Rao"

      - name: Push to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
